<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Каталог");
?>

<?$APPLICATION->IncludeComponent(
	"bitrix:catalog", 
	"perfectum_catalog", 
	array(
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "12",
		"HIDE_NOT_AVAILABLE" => "N",
		"BASKET_URL" => "/personal/cart/",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SEF_MODE" => "Y",
		"SEF_FOLDER" => "/catalog/",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"ADD_ELEMENT_CHAIN" => "N",
		"USE_ELEMENT_COUNTER" => "Y",
		"USE_FILTER" => "Y",
		"FILTER_NAME" => "arrFilter",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "",
			1 => "BRAND_REF",
			2 => "",
		),
		"FILTER_PRICE_CODE" => array(
			0 => "BASE",
		),
		"FILTER_OFFERS_FIELD_CODE" => array(
			0 => "PREVIEW_PICTURE",
			1 => "DETAIL_PICTURE",
			2 => "",
		),
		"FILTER_OFFERS_PROPERTY_CODE" => array(
			0 => "ARTNUMBER",
			1 => "COLOR_R",
			2 => "SIZES_CLOTHES",
			3 => "SIZES_SHOES",
			4 => "",
		),
		"USE_REVIEW" => "Y",
		"MESSAGES_PER_PAGE" => "10",
		"USE_CAPTCHA" => "Y",
		"REVIEW_AJAX_POST" => "Y",
		"PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
		"FORUM_ID" => "1",
		"URL_TEMPLATES_READ" => "",
		"SHOW_LINK_TO_FORUM" => "Y",
		"USE_COMPARE" => "N",
		"COMPARE_NAME" => "CATALOG_COMPARE_LIST",
		"COMPARE_FIELD_CODE" => array(
			0 => "PREVIEW_PICTURE",
			1 => "DETAIL_PICTURE",
			2 => "",
		),
		"COMPARE_PROPERTY_CODE" => array(
			0 => "",
			1 => "WARRANTY",
			2 => "MANUFACTURER",
			3 => "COUNTRY",
			4 => "",
		),
		"COMPARE_OFFERS_FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_PICTURE",
			2 => "DETAIL_PICTURE",
			3 => "",
		),
		"COMPARE_OFFERS_PROPERTY_CODE" => array(
			0 => "COLOR_R",
			1 => "SIZES_CLOTHES",
			2 => "SIZES_SHOES",
			3 => "",
		),
		"COMPARE_ELEMENT_SORT_FIELD" => "catalog_PRICE_1",
		"COMPARE_ELEMENT_SORT_ORDER" => "asc",
		"DISPLAY_ELEMENT_SELECT_BOX" => "N",
		"PRICE_CODE" => array(
			0 => "BASE",
		),
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "N",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"CONVERT_CURRENCY" => "Y",
		"CURRENCY_ID" => "BYN",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"USE_PRODUCT_QUANTITY" => "Y",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PARTIAL_PRODUCT_PROPERTIES" => "Y",
		"PRODUCT_PROPERTIES" => array(
		),
		"OFFERS_CART_PROPERTIES" => array(
			0 => "ARTNUMBER",
			1 => "COLOR_R",
			2 => "SIZES_CLOTHES",
			3 => "SIZES_SHOES",
		),
		"SHOW_TOP_ELEMENTS" => "N",
		"SECTION_COUNT_ELEMENTS" => "Y",
		"SECTION_TOP_DEPTH" => "1",
		"SECTIONS_VIEW_MODE" => "TEXT",
		"SECTIONS_SHOW_PARENT_NAME" => "Y",
		"PAGE_ELEMENT_COUNT" => "40",
		"LINE_ELEMENT_COUNT" => "2",
		"ELEMENT_SORT_FIELD" => "catalog_PRICE_1",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_FIELD2" => "catalog_PRICE_1",
		"ELEMENT_SORT_ORDER2" => "asc",
		"LIST_PROPERTY_CODE" => array(
			0 => "NEWPRODUCT",
			1 => "SPECIALOFFER",
			2 => "WARRANTY",
			3 => "",
		),
		"INCLUDE_SUBSECTIONS" => "Y",
		"LIST_META_KEYWORDS" => "UF_KEYWORDS",
		"LIST_META_DESCRIPTION" => "UF_META_DESCRIPTION",
		"LIST_BROWSER_TITLE" => "UF_BROWSER_TITLE",
		"LIST_OFFERS_FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_PICTURE",
			2 => "DETAIL_PICTURE",
			3 => "",
		),
		"LIST_OFFERS_PROPERTY_CODE" => array(
			0 => "ARTNUMBER",
			1 => "COLOR_R",
			2 => "SIZES_CLOTHES",
			3 => "SIZES_SHOES",
			4 => "MORE_PHOTO",
			5 => "SIZES_C",
			6 => "",
		),
		"LIST_OFFERS_LIMIT" => "0",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "",
			1 => "WARRANTY",
			2 => "MANUFACTURER",
			3 => "COUNTRY",
			4 => "COMPOSITION",
			5 => "CODE",
			6 => "LENGTH",
			7 => "SLEEVE",
			8 => "CLASP",
			9 => "SEASON",
			10 => "STYLE",
			11 => "COLLECTION",
			12 => "SIZE_TYPE",
			13 => "DRESS_TYPE",
			14 => "TYPE_JEANS_PANTS",
			15 => "ATTRITION",
			16 => "TYPE_HEEL",
			17 => "SHOE_DETAILS",
			18 => "HEEL_HEIGHT",
			19 => "UPPER_MATERIAL",
			20 => "INNER_MATERIAL",
			21 => "MATERIAL_INSOLE",
			22 => "MATERIAL_SOLE",
			23 => "COLOR",
			24 => "",
		),
		"DETAIL_META_KEYWORDS" => "-",
		"DETAIL_META_DESCRIPTION" => "-",
		"DETAIL_BROWSER_TITLE" => "-",
		"DETAIL_OFFERS_FIELD_CODE" => array(
			0 => "NAME",
			1 => "",
		),
		"DETAIL_OFFERS_PROPERTY_CODE" => array(
			0 => "ARTNUMBER",
			1 => "COLOR_R",
			2 => "SIZES_CLOTHES",
			3 => "SIZES_SHOES",
			4 => "",
		),
		"LINK_IBLOCK_TYPE" => "",
		"LINK_IBLOCK_ID" => "",
		"LINK_PROPERTY_SID" => "",
		"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
		"USE_ALSO_BUY" => "Y",
		"ALSO_BUY_ELEMENT_COUNT" => "5",
		"ALSO_BUY_MIN_BUYES" => "1",
		"USE_STORE" => "N",
		"USE_STORE_PHONE" => "Y",
		"USE_STORE_SCHEDULE" => "Y",
		"USE_MIN_AMOUNT" => "Y",
		"STORE_PATH" => "/site_zf/about/store/#store_id#",
		"MAIN_TITLE" => "Наличие на складах",
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_FIELD2" => "id",
		"OFFERS_SORT_ORDER2" => "desc",
		"PAGER_TEMPLATE" => "pagenav",
		"DISPLAY_TOP_PAGER" => "Y",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Товары",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000000",
		"PAGER_SHOW_ALL" => "N",
		"ADD_PICT_PROP" => "MORE_PHOTO",
		"LABEL_PROP" => "-",
		"PRODUCT_DISPLAY_MODE" => "Y",
		"OFFER_ADD_PICT_PROP" => "MORE_PHOTO",
		"OFFER_TREE_PROPS" => array(
			0 => "COLOR_R",
			1 => "SIZES_CLOTHES",
			2 => "SIZES_SHOES",
		),
		"SHOW_DISCOUNT_PERCENT" => "Y",
		"SHOW_OLD_PRICE" => "Y",
		"DETAIL_SHOW_MAX_QUANTITY" => "N",
		"MESS_BTN_BUY" => "В корзину",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_COMPARE" => "Сравнение",
		"MESS_BTN_DETAIL" => "Подробнее",
		"QUICK_LOOK_PARAMS" => "QUICK_LOOK_BUTTON",
		"MAX_WIDTH" => "300",
		"MAX_HEIGHT" => "400",
		"DETAIL_USE_COMMENTS" => "Y",
		"DETAIL_BLOG_USE" => "Y",
		"DETAIL_BRAND_USE" => "Y",
		"DETAIL_BRAND_PROP_CODE" => array(
			0 => "",
			1 => "BRAND_REF",
			2 => "",
		),
		"ON_PREVIEW_TEXT" => "Y",
		"DELIVERY_PROP_CODE" => "DELIVERY",
		"USE_RATING" => "Y",
		"USE_FAVORITES" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"CATALOG_SEO_TEXT" => "CATALOG_SEO_TEXT_DOWN",
		"USE_CATALOG_CREDIT" => "Y",
		"LINK_CATALOG_CREDIT" => "credit/",
		"LIST_PROPERTY_CODE_CHARACTERISTICS" => array(
			0 => "WARRANTY",
			1 => "MANUFACTURER",
			2 => "COUNTRY",
			3 => "NUMBER_OF_SIM_CARDS",
			4 => "ENCLOSURE_TYPE",
			5 => "PLATFORM",
			6 => "DIAGONAL_SCREEN",
			7 => "",
		),
		"DETAIL_LIST_PROPERTY_CODE_CHARACTERISTICS" => array(
			0 => "WARRANTY",
			1 => "MANUFACTURER",
			2 => "COUNTRY",
			3 => "NUMBER_OF_SIM_CARDS",
			4 => "ENCLOSURE_TYPE",
			5 => "PLATFORM",
			6 => "DIAGONAL_SCREEN",
			7 => "MATERIAL_KORPUS",
			8 => "MOBILE_NTERFACES",
			9 => "WIDTH",
			10 => "HEIGHT",
			11 => "THICKNESS",
			12 => "WEIGHT",
			13 => "",
		),
		"USE_ZOOM" => "N",
		"ZOOM" => "inner",
		"ZOOM_LENS_COLOUR" => "#c9dae6",
		"ZOOM_LENS_BORDER" => "0",
		"ZOOM_LENS_LENS_SHAPE" => "round",
		"ZOOM_LENS_BORDER_SIZE" => "1",
		"ZOOM_LENS_BORDER_SIZE_COLOR" => "#dcdcdc",
		"ZOOM_EASING" => "0",
		"ZOOM_MOUSEWHEELZOOM" => "0",
		"ZOOM_CURSOR" => "crosshair",
		"ZOOM_WINDOW_POSITION" => "1",
		"ZOOM_WINDOW_OFFETX" => "10",
		"ZOOM_WINDOW_WIDTH" => "500",
		"ZOOM_WINDOW_HEIGHT" => "500",
		"ZOOM_LENS_SIZE" => "200",
		"SLIDER_IMAGES" => "fade",
		"SLIDER_IMAGES_FADE_SPEED" => "300",
		"SLIDER_MINIIMAGES_FADE_SPEED" => "600",
		"USE_SALES" => "Y",
		"USE_BUY_ONE_CLICK" => "Y",
		"PROP_CODE_ACCESSORIES" => "ACCESSORIES",
		"PROP_CODE_DOCUMENTATIONS" => "DOCUMENTATIONS",
		"COMPONENT_TEMPLATE" => "perfectum_catalog",
		"USE_MAIN_ELEMENT_SECTION" => "N",
		"SET_LAST_MODIFIED" => "N",
		"SECTION_BACKGROUND_IMAGE" => "-",
		"DETAIL_SET_CANONICAL_URL" => "Y",
		"DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
		"DETAIL_BACKGROUND_IMAGE" => "-",
		"SHOW_DEACTIVATED" => "N",
		"STORES" => array(
			0 => "1",
			1 => "2",
			2 => "3",
			3 => "4",
			4 => "",
		),
		"USER_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"FIELDS" => array(
			0 => "PHONE",
			1 => "SCHEDULE",
			2 => "EMAIL",
			3 => "",
		),
		"SHOW_EMPTY_STORE" => "Y",
		"SHOW_GENERAL_STORE_INFORMATION" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SHOW_404" => "N",
		"MESSAGE_404" => "",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",
		"DETAIL_SET_VIEWED_IN_COMPONENT" => "N",
		"COMMON_SHOW_CLOSE_POPUP" => "Y",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"DETAIL_USE_VOTE_RATING" => "Y",
		"DETAIL_BLOG_URL" => "catalog_comments",
		"DETAIL_BLOG_EMAIL_NOTIFY" => "N",
		"DETAIL_VK_USE" => "N",
		"DETAIL_FB_USE" => "N",
		"USE_SALE_BESTSELLERS" => "Y",
		"USE_COMMON_SETTINGS_BASKET_POPUP" => "N",
		"COMMON_ADD_TO_BASKET_ACTION" => "",
		"TOP_ADD_TO_BASKET_ACTION" => "ADD",
		"SECTION_ADD_TO_BASKET_ACTION" => "ADD",
		"DETAIL_ADD_TO_BASKET_ACTION" => array(
			0 => "ADD",
		),
		"DETAIL_SHOW_BASIS_PRICE" => "Y",
		"DETAIL_DISPLAY_NAME" => "Y",
		"DETAIL_DETAIL_PICTURE_MODE" => "IMG",
		"DETAIL_ADD_DETAIL_TO_SLIDER" => "Y",
		"DETAIL_DISPLAY_PREVIEW_TEXT_MODE" => "E",
		"USE_BIG_DATA" => "Y",
		"BIG_DATA_RCM_TYPE" => "personal",
		"USE_GIFTS_DETAIL" => "Y",
		"USE_GIFTS_SECTION" => "Y",
		"USE_GIFTS_MAIN_PR_SECTION_LIST" => "Y",
		"GIFTS_DETAIL_PAGE_ELEMENT_COUNT" => "4",
		"GIFTS_DETAIL_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_DETAIL_BLOCK_TITLE" => "Выберите один из подарков",
		"GIFTS_DETAIL_TEXT_LABEL_GIFT" => "Подарок",
		"GIFTS_SECTION_LIST_PAGE_ELEMENT_COUNT" => "3",
		"GIFTS_SECTION_LIST_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_SECTION_LIST_BLOCK_TITLE" => "Подарки к товарам этого раздела",
		"GIFTS_SECTION_LIST_TEXT_LABEL_GIFT" => "Подарок",
		"GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
		"GIFTS_SHOW_OLD_PRICE" => "Y",
		"GIFTS_SHOW_NAME" => "Y",
		"GIFTS_SHOW_IMAGE" => "Y",
		"GIFTS_MESS_BTN_BUY" => "Выбрать",
		"GIFTS_MAIN_PRODUCT_DETAIL_PAGE_ELEMENT_COUNT" => "3",
		"GIFTS_MAIN_PRODUCT_DETAIL_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_MAIN_PRODUCT_DETAIL_BLOCK_TITLE" => "Выберите один из товаров, чтобы получить подарок",
		"DETAIL_VOTE_DISPLAY_AS_RATING" => "rating",
		"FILTER_VIEW_MODE" => "vertical",
		"MESS_BTN_ADDED_TO_BASKET" => "В корзине",
		"HOVER_IMAGE" => "Y",
		"MIN_AMOUNT" => "10",
		"CAROUSEL_DOTS_VERTICAL" => "Y",
		"SKU_VIEW" => "LIST2",
		"USE_QUICKVIEW" => "Y",
		"USE_SKU_TOOLTIP" => "N",
		"USE_ONECLICK" => "Y",
		"ONECLICK_USE_CAPTCHA" => "N",
		"ONECLICK_MESS_TITLE" => "Купить в один клик",
		"ONECLICK_OK_TEXT" => "Спасибо за заказ! В ближайшее время наш менеджер свяжется с вами.",
		"ONECLICK_EMAIL_TO" => "pult.by@gmail.com",
		"ONECLICK_INCLUDE_FIELDS" => array(
			0 => "NAME",
			1 => "EMAIL",
			2 => "PHONE",
			3 => "MESSAGE",
		),
		"ONECLICK_REQUIRED_FIELDS" => array(
			0 => "NAME",
			1 => "PHONE",
		),
		"ONECLICK_EVENT_MESSAGE_ID" => array(
			0 => "47",
		),
		"ONECLICK_USE_MASK" => "Y",
		"ONECLICK_MASK_PHONE" => "+375 (99) 999-99-99",
		"HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"USER_CONSENT" => "N",
		"USER_CONSENT_ID" => "0",
		"USER_CONSENT_IS_CHECKED" => "Y",
		"USER_CONSENT_IS_LOADED" => "N",
		"DETAIL_STRICT_SECTION_CHECK" => "N",
		"ONECLICK_USER_CONSENT" => "N",
		"COMPATIBLE_MODE" => "Y",
		"SEF_URL_TEMPLATES" => array(
			"sections" => "",
			"section" => "#SECTION_CODE#/",
			"element" => "#SECTION_CODE#/#ELEMENT_CODE#.html",
			"compare" => "compare/",
			"smart_filter" => "#SECTION_CODE#/filter/#SMART_FILTER_PATH#/apply/",
		)
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>