<?$APPLICATION->IncludeComponent("bitrix:news.line", "news", array(
	"ACTIVE_DATE_FORMAT" => "j F Y",
		"ALL_LINK" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"FIELD_CODE" => array(
			0 => "PREVIEW_TEXT",
			1 => "PREVIEW_PICTURE",
			2 => "",
		),
		"HIDDEN_BUTTON_MORE" => "Y",
		"IBLOCKS" => array(
			0 => "5",
		),
		"IBLOCK_TYPE" => "news",
		"MAX_HEIGHT" => "200",
		"MAX_WIDTH" => "280",
		"MESS_TITLE" => "Акции",
		"MESS_TITLE_LINK" => "Y",
		"MODE_VIEW" => "TOP",
		"MOUSE_DRAG" => "Y",
		"NEWS_COUNT" => "6",
		"PREVIEW_TRUNCATE_LEN" => "160",
		"RESPONSIVE_CAROUSEL_ITEMS_LG" => "3",
		"RESPONSIVE_CAROUSEL_ITEMS_MD" => "3",
		"RESPONSIVE_CAROUSEL_ITEMS_MOBILE" => "1",
		"RESPONSIVE_CAROUSEL_ITEMS_SM" => "3",
		"RESPONSIVE_CAROUSEL_ITEMS_XS" => "2",
		"RESPONSIVE_ITEMS_LG" => "3",
		"RESPONSIVE_ITEMS_MD" => "3",
		"RESPONSIVE_ITEMS_SM" => "4",
		"RESPONSIVE_ITEMS_XS" => "6",
		"SLIDER_AUTOPLAY" => "N",
		"SLIDER_AUTOPLAY_HOVER_PAUSE" => "N",
		"SLIDER_LOOP" => "N",
		"SLIDER_NAV" => "Y",
		"SLIDER_SHOW_SPEED" => "8000",
		"SLIDER_SPEED" => "1000",
		"SORT_BY1" => "SORT",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"USE_CAROUSEL" => "Y"
	),
	false,
	array(
	"ACTIVE_COMPONENT" => "N"
	)
);?>