<?$APPLICATION->IncludeComponent("bitrix:catalog.brandblock", "brand_main", array(
	"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"ELEMENT_CODE" => "",
		"ELEMENT_COUNT" => "20",
		"ELEMENT_ID" => "",
		"FILTER_NAME" => "arrFilter",
		"HEIGHT" => "80",
		"HEIGHT_SMALL" => "80",
		"IBLOCK_ID" => "9",
		"IBLOCK_TYPE" => "catalog",
		"MESS_TITLE" => "Бренды",
		"MESS_TITLE_LINK" => "Y",
		"MOUSE_DRAG" => "Y",
		"PROP_CODE" => array(
			0 => "BRAND_REF",
			1 => "",
		),
		"RESPONSIVE_CAROUSEL_ITEMS_LG" => "6",
		"RESPONSIVE_CAROUSEL_ITEMS_MD" => "5",
		"RESPONSIVE_CAROUSEL_ITEMS_MOBILE" => "2",
		"RESPONSIVE_CAROUSEL_ITEMS_SM" => "4",
		"RESPONSIVE_CAROUSEL_ITEMS_XS" => "3",
		"SHOW_DEACTIVATED" => "N",
		"SINGLE_COMPONENT" => "Y",
		"SLIDER_AUTOPLAY" => "N",
		"SLIDER_AUTOPLAY_HOVER_PAUSE" => "N",
		"SLIDER_LOOP" => "Y",
		"SLIDER_NAV" => "Y",
		"SLIDER_SHOW_SPEED" => "8000",
		"SLIDER_SPEED" => "1000",
		"WIDTH" => "100",
		"WIDTH_SMALL" => "100"
	),
	false,
	array(
	"ACTIVE_COMPONENT" => "Y"
	)
);?>